#!/usr/bin/env zsh
# Requires:
#   brew install jq
#   conda create -n things python
#   conda activate things
#   pip install things-cli

source /opt/anaconda3/etc/profile.d/conda.sh
conda activate things

things-cli --json search "" | jq -r 'map(select(.project_title != null)) | sort_by(.created)[] | "- [ ] \(.created) \(.title) (\(.project_title))"'
